#!/usr/bin/env bash
# Builds core, alloc and compiler_builtins for the Horizon Rust target
# and installs them where a bare `rustc --sysroot` finds them.
#
#   scripts/build-rust-sysroot.sh [--force]
#
# WHY A SYSROOT AND NOT CARGO. Meson drives rustc directly and never
# calls cargo (mesonbuild/compilers/rust.py: the command line is
# `rustc --emit link=... source.rs`). So the standard library cannot be
# supplied the way a cargo project would supply it, with -Zbuild-std in
# the build itself. It has to already be on disk, in the layout rustc
# looks for:
#
#   <sysroot>/lib/rustlib/<target>/lib/*.rlib
#
# Cargo is used here as a *build-time tool* to produce those three
# rlibs, and then gets out of the way. Measured: after this install, a
# plain `rustc --target ... --sysroot <dir> --crate-type staticlib`
# compiles a no_std + alloc crate with no cargo anywhere.
#
# WHY core AND alloc AND NOT std. aarch64-nintendo-switch-freestanding
# reports `"std": false` and has no `target_family`, so a std built for
# it selects Rust's `sys/pal/unsupported` — the parts of std that make
# it worth having return errors, measured directly against this target.
# NAK and NIL are made no_std by mesa-patches/ instead.
#
# ONLY FOR A LOCAL devkitA64 INSTALL. In container mode the sysroot is
# baked into the derived toolchain image instead
# (toolchain/Dockerfile, scripts/build-toolchain-image.sh), because
# that is where the rustc that has to load these rlibs lives: an rlib
# records the compiler's metadata version, and one built by a different
# rustc fails with "found crate `core` compiled by an incompatible
# version". Keeping the sysroot next to its compiler is what stops that
# happening.
#
# Idempotent: an installed sysroot whose stamp matches the current
# rustc and target is left alone. --force rebuilds it.
#
# Copyright (c) mesa-nvk-horizon contributors
# SPDX-License-Identifier: MIT
set -eu
cd "$(dirname "$0")/.."

# shellcheck source=toolchain-env.sh
. scripts/toolchain-env.sh

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ "$HORIZON_IN_CONTAINER" -eq 1 ]; then
    echo "build-rust-sysroot: the toolchain is an image, so the sysroot"
    echo "                    is built into it. Run"
    echo "                    scripts/build-toolchain-image.sh instead."
    exit 0
fi

SYSROOT="$HORIZON_RUST_SYSROOT"
# The throwaway cargo package -Zbuild-std is invoked through. It exists
# only to give cargo a target directory and a profile; nothing in it
# ends up in the sysroot.
DRIVER=build/toolchain/rust-sysroot-src
STAMP="$SYSROOT/.stamp"

# --- what the sysroot was built from, in one line --------------------
#
# rustc's version and the target name are the two inputs that decide
# whether the installed rlibs are still usable: an rlib carries the
# compiler's metadata version, and loading it with a different rustc
# fails with "found crate `core` compiled by an incompatible version".
# The nightly floats by policy (R15, toolchain/versions.env), so this
# has to be checked rather than assumed stable.
sysroot_identity() {
    horizon_run rustc --version | tr -d '\r'
    echo "target=$RUST_TARGET"
}

if [ "$FORCE" -eq 0 ] && [ -f "$STAMP" ] &&
   [ "$(sysroot_identity)" = "$(cat "$STAMP")" ]; then
    echo "build-rust-sysroot: $SYSROOT is current ($(
        head -n1 "$STAMP"))"
    exit 0
fi

# --- the vendored crates.io packages -Zbuild-std resolves ------------
if [ ! -f build/toolchain/rust-cargo-config.toml ] ||
   [ ! -d build/toolchain/rust-vendor ]; then
    echo "build-rust-sysroot: vendoring the crates -Zbuild-std needs"
    scripts/fetch-rust-crates.sh
fi

# --- the driver package ----------------------------------------------
#
# Written every run rather than committed: it is generated input, it is
# three files, and regenerating it means a change here cannot be masked
# by a stale copy under build/.
mkdir -p "$DRIVER/src"
cat > "$DRIVER/Cargo.toml" <<'EOF'
# GENERATED by scripts/build-rust-sysroot.sh — do not edit.
#
# A package that exists only so cargo has something to be invoked on.
# -Zbuild-std compiles core and alloc as dependencies of *this*, and
# those artefacts are what gets installed. The crate itself is dropped.
[package]
name = "horizon-sysroot-driver"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

# The target spec already says panic = abort. Stating it here as well
# keeps the driver's own profile from disagreeing with the target and
# asking for an unwinder that does not exist.
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
EOF
cat > "$DRIVER/src/lib.rs" <<'EOF'
// GENERATED by scripts/build-rust-sysroot.sh — do not edit.
#![no_std]
extern crate alloc;
EOF
# The source replacement goes in CARGO_HOME, not in the package's own
# .cargo/config.toml. Cargo discovers a package-local config by walking
# up from the *current directory*, not from --manifest-path, and this
# script runs from the repository root — so a config beside the driver
# was silently ignored and cargo went looking for crates.io:
#
#   error: no matching package named `rustc-literal-escaper` found
#   location searched: crates.io index
#
# with the crate sitting vendored on disk the whole time. CARGO_HOME is
# read wherever cargo is invoked from, which is what this needs.
CARGO_HOME_DIR=build/toolchain/cargo-home
mkdir -p "$CARGO_HOME_DIR"
cp build/toolchain/rust-cargo-config.toml "$CARGO_HOME_DIR/config.toml"

# --- build ------------------------------------------------------------
#
# --release, not the default dev profile. An unoptimised core is both
# enormous and slow, and Mesa is configured --buildtype=plain, so
# nothing downstream would ever ask for a debug standard library.
#
# CARGO_HOME under build/: the image's /opt/cargo is not writable from
# every environment, and a build must not scribble in the toolchain.
echo "build-rust-sysroot: building core+alloc for $RUST_TARGET"
horizon_run env \
    CARGO_HOME="$PWD/$CARGO_HOME_DIR" \
    cargo build \
        --manifest-path "$PWD/$DRIVER/Cargo.toml" \
        --target-dir "$PWD/$DRIVER/target" \
        --offline --release \
        -Z build-std=core,alloc \
        --target "$RUST_TARGET"

# --- install ----------------------------------------------------------
LIBDIR="$SYSROOT/lib/rustlib/$RUST_TARGET/lib"
rm -rf "$SYSROOT"
mkdir -p "$LIBDIR"

DEPS="$DRIVER/target/$RUST_TARGET/release/deps"
n=0
for rlib in "$DEPS"/*.rlib; do
    [ -f "$rlib" ] || continue
    base=$(basename "$rlib")
    # The driver crate itself is not part of the standard library.
    # rustc prefixes rlibs with "lib", so the pattern has to as well —
    # without it the driver was installed into the sysroot too.
    case "$base" in libhorizon_sysroot_driver-*) continue ;; esac
    cp "$rlib" "$LIBDIR/"
    n=$((n + 1))
done

# Fail loudly rather than install a sysroot missing the crate every
# later build depends on. Without this the first symptom is Mesa's
# rustc sanity check failing with E0463 again, several scripts away
# from the cause.
for want in core alloc compiler_builtins; do
    # shellcheck disable=SC2144 # a glob is exactly the question here
    if ! ls "$LIBDIR/lib${want}-"*.rlib >/dev/null 2>&1; then
        echo "error: $want is missing from the built sysroot." >&2
        echo "       $LIBDIR holds: $(ls "$LIBDIR" | tr '\n' ' ')" >&2
        exit 1
    fi
done

# rustc resolves *host* artefacts through the sysroot too — proc-macro
# crates are host dylibs, and Mesa builds three of them. Pointing the
# host directory at the real rustup sysroot's copy keeps that working
# without duplicating it. A symlink, because the target is outside the
# tree and can be large.
HOST_TRIPLE=$(horizon_run rustc -vV | sed -n 's/^host: //p' | tr -d '\r')
REAL_SYSROOT=$(horizon_run rustc --print sysroot | tr -d '\r')
if [ -n "$HOST_TRIPLE" ] && [ -n "$REAL_SYSROOT" ]; then
    ln -sfn "$REAL_SYSROOT/lib/rustlib/$HOST_TRIPLE" \
            "$SYSROOT/lib/rustlib/$HOST_TRIPLE"
    echo "build-rust-sysroot: host libdir ($HOST_TRIPLE) linked to the" \
         "toolchain's own"
fi

sysroot_identity > "$STAMP"
echo "build-rust-sysroot: installed $n rlib(s) in $LIBDIR"
ls "$LIBDIR" | sed 's/^/  /'
