#!/usr/bin/env bash
# Writes the pieces of the Meson cross configuration that cannot be
# committed: the absolute location of devkitPro on *this* machine, and
# of the compat archive inside this checkout.
#
# toolchain/horizon-aarch64.cross is path-free and references those
# constants without defining them. Meson shares [constants] across every
# --cross-file on a command line, so this generated file supplies them:
#
#   meson setup --cross-file build/toolchain/devkitpro.cross \
#               --cross-file toolchain/horizon-aarch64.cross ...
#
# Output goes under build/ (gitignored) — it is machine-specific by
# construction and must never be committed.
#
# Idempotent: re-running with the same $DEVKITPRO rewrites identical
# content and reports "unchanged", so it does not force Meson to
# reconfigure.
#
# Copyright (c) mesa-nvk-horizon contributors
# SPDX-License-Identifier: MIT
set -eu
cd "$(dirname "$0")/.."

# shellcheck source=toolchain-env.sh
. scripts/toolchain-env.sh

OUT="${1:-$HORIZON_CROSS_CONST_FILE}"

mkdir -p "$(dirname "$OUT")"

tmp="$OUT.tmp.$$"
cat > "$tmp" <<EOF
# GENERATED by scripts/gen-cross-file.sh — do not commit, do not edit.
# Supplies the constants toolchain/horizon-aarch64.cross deliberately
# leaves undefined, because defining them would mean writing an absolute
# path into a tracked file.
[constants]
devkitpro = '$HORIZON_DEVKITPRO'
horizon_compat_libdir = '$PWD/$HORIZON_COMPAT_LIBDIR'
EOF

if [ -f "$OUT" ] && cmp -s "$tmp" "$OUT"; then
    rm -f "$tmp"
    echo "gen-cross-file: $OUT unchanged"
else
    mv "$tmp" "$OUT"
    echo "gen-cross-file: wrote $OUT (devkitpro = $HORIZON_DEVKITPRO)"
fi
