#!/usr/bin/env bash
# Writes the build-id header every test prints in its first lines.
#
#   scripts/gen-build-id.sh            # to stdout (Meson captures it)
#   scripts/gen-build-id.sh <outfile>  # to a file (the Makefile)
#
# WHY THIS EXISTS, AND IT COST A HARDWARE RUN. A .nro on an SD card
# looks exactly like the .nro it replaced. On 2026-08-05 a run came back
# with results identical to the previous one — same failures, same
# counts — and the reason took a while to find: the binaries that ran
# were the previous build's. Nothing in the log said which build
# produced it, so "the fix did not work" and "the fix was not there"
# were indistinguishable, and the first reading was the wrong one.
#
# The only reason it was caught at all is that Mesa's vk_logi prints
# __FILE__ and __LINE__, and a line number had moved. That is luck, not
# a mechanism.
#
# So: every log now starts with a stamp that changes on every build, and
# the run instructions say which stamp to expect. A stale binary
# announces itself in its first two lines.
#
# WHAT IT COSTS. testfw.o is recompiled on every build and every .nro
# therefore differs from the last one, so scripts/package-horizon.sh
# copies all of them every time. That is the price of the artefact being
# able to name itself, and it is small: one object, and a manifest whose
# whole job was always to attribute an artefact to one build.
#
# The stamp is UTC and second-resolution, plus the repository's HEAD
# when there is one. Not a content hash: the point is to tell two builds
# apart, and two builds of the same source ARE different artefacts once
# one of them is the one on the SD card.
#
# Copyright (c) mesa-nvk-horizon contributors
# SPDX-License-Identifier: MIT
set -eu
cd "$(dirname "$0")/.."

# Milliseconds, because seconds are not enough. Review of PR #8: two
# builds within the same second over the same HEAD produce identical
# stamps, and telling two builds apart is the whole job — the run-11
# failure was exactly a binary that could not be told from another.
stamp=$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)

# Short HEAD, when this is a git checkout and git is available. A tree
# with local edits says so, because "the commit it was built from" is a
# different claim from "the tree it was built from".
# mesa/.gitkeep belongs to *this* repository — it is what keeps the
# directory in git while its contents are ignored — so it is always
# untracked inside the Mesa checkout and is not a modification of Mesa.
# Filtered here for the same reason fetch-mesa.sh, apply-mesa-patches.sh
# and fetch-mesa-subprojects.sh filter it: a dirty marker that is always
# on is not a marker.
# The top-level test is not decoration. `git -C mesa` walks *up* when
# mesa/ is not itself a repository, and mesa/ is exactly that on any
# tree where fetch-mesa.sh has not run — it holds one .gitkeep belonging
# to this repository. So this used to answer with the outer HEAD and the
# stamp read `mesa:9053687`, which is a claim that Mesa is at a commit
# that is this repository's commit. Measured on a tree with mesa/
# unpopulated: `git -C mesa rev-parse --show-toplevel` reports the
# mesa-nvk-horizon root.
#
# That is the one thing this stamp exists to prevent, aimed at itself:
# an artefact attributed to sources it was not built from. It reaches
# published packages too, since .github/workflows/release.yml builds
# without Mesa. Same guard as scripts/apply-mesa-patches.sh:110-120 —
# ask git where the repository actually is, not whether it found one.
_describe() { # dir -> "<short-head>[-dirty]" or "nogit"
    if command -v git >/dev/null 2>&1 &&
       git -C "$1" rev-parse --git-dir >/dev/null 2>&1 &&
       [ "$(cd "$1" && pwd -P)" = \
         "$(cd "$(git -C "$1" rev-parse --show-toplevel)" && pwd -P)" ]; then
        _h=$(git -C "$1" rev-parse --short HEAD 2>/dev/null || echo unknown)
        if [ -n "$(git -C "$1" status --porcelain 2>/dev/null |
                   grep -v '^?? \.gitkeep$' || true)" ]; then
            _h="$_h-dirty"
        fi
        echo "$_h"
    else
        echo "nogit"
    fi
}

head=$(_describe .)

# AND MESA'S, BECAUSE MESA IS WHAT THE DRIVER IS BUILT FROM.
#
# mesa/ is a separate checkout, gitignored by this repository, holding
# the NVK and WSI sources every driver-linked test actually links. The
# outer HEAD says nothing about it: an edit under mesa/src — which is
# where every patch in mesa-patches/ lands — leaves this repository
# clean, and a stamp built only from the outer tree would attribute a
# hardware result to sources that were not the ones compiled.
#
# That is not hypothetical here. On 2026-08-08 a batch shipped with a
# libvulkan_wsi.a three days older than the patch it was meant to carry,
# and nothing in the stamp could have said so.
if [ -d mesa ]; then
    head="$head mesa:$(_describe mesa)"
fi

emit() {
    echo "/* GENERATED by scripts/gen-build-id.sh — do not edit. */"
    echo "#ifndef HORIZON_BUILD_ID_H"
    echo "#define HORIZON_BUILD_ID_H"
    echo "#define HORIZON_BUILD_ID \"$stamp $head\""
    echo "#endif"
}

if [ "$#" -ge 1 ]; then
    emit > "$1"
else
    emit
fi
