#!/usr/bin/env bash
# Writes the build-id header every test prints in its first lines.
#
#   scripts/gen-build-id.sh            # to stdout (Meson captures it)
#   scripts/gen-build-id.sh <outfile>  # to a file (the Makefile)
#
# WHY THIS EXISTS, AND IT COST A HARDWARE RUN. A .nro on an SD card
# looks exactly like the .nro it replaced. On 2026-08-05 a run came back
# with results identical to the previous one — same failures, same
# counts — and the reason took a while to find: the binaries that ran
# were the previous build's. Nothing in the log said which build
# produced it, so "the fix did not work" and "the fix was not there"
# were indistinguishable, and the first reading was the wrong one.
#
# The only reason it was caught at all is that Mesa's vk_logi prints
# __FILE__ and __LINE__, and a line number had moved. That is luck, not
# a mechanism.
#
# So: every log now starts with a stamp that changes on every build, and
# the run instructions say which stamp to expect. A stale binary
# announces itself in its first two lines.
#
# WHAT IT COSTS. testfw.o is recompiled on every build and every .nro
# therefore differs from the last one, so scripts/package-horizon.sh
# copies all of them every time. That is the price of the artefact being
# able to name itself, and it is small: one object, and a manifest whose
# whole job was always to attribute an artefact to one build.
#
# The stamp is UTC and second-resolution, plus the repository's HEAD
# when there is one. Not a content hash: the point is to tell two builds
# apart, and two builds of the same source ARE different artefacts once
# one of them is the one on the SD card.
#
# Copyright (c) mesa-nvk-horizon contributors
# SPDX-License-Identifier: MIT
set -eu
cd "$(dirname "$0")/.."

stamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Short HEAD, when this is a git checkout and git is available. A tree
# with local edits says so, because "the commit it was built from" is a
# different claim from "the tree it was built from".
head="nogit"
if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
    head=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
        head="$head-dirty"
    fi
fi

emit() {
    echo "/* GENERATED by scripts/gen-build-id.sh — do not edit. */"
    echo "#ifndef HORIZON_BUILD_ID_H"
    echo "#define HORIZON_BUILD_ID_H"
    echo "#define HORIZON_BUILD_ID \"$stamp $head\""
    echo "#endif"
}

if [ "$#" -ge 1 ]; then
    emit > "$1"
else
    emit
fi
