#!/usr/bin/env python3
# Emits the four fragment shaders of the convergence-stack matrix.
#
#   scripts/gen-crs-matrix.py            # writes tests/shaders/crs_mx_*.spvasm
#   scripts/gen-crs-matrix.py --check    # fails if they are out of date
#
# WHY A GENERATOR AND NOT FOUR HAND-WRITTEN FILES. The experiment is two
# knobs — how deep the convergence stack goes, and how many values stay
# live across it — crossed with each other, and the whole value of the
# matrix is that the four shaders differ in *only* those two. Four
# hand-written files of three hundred lines each cannot be read for that
# property; one template with two parameters can. The generated files are
# committed anyway, because the build consumes `.spvasm` and a build must
# not need Python.
#
# WHAT THE TWO KNOBS ARE FOR, and this is the part that has already
# caused a wrong conclusion once (see docs/MEASURED-ON-HARDWARE.md):
#
#   levels   how many nested divergent `if`s the nest has. This is NOT
#            the compiled convergence-stack depth — from_nir pushes once
#            per divergent construct, the loop included, and the shader
#            model then turns that depth into a reservation through
#            crs_size(), which is zero at or below sixteen on sm50 and
#            1024 above it. Only the compiler can say what a given source
#            produced, which is what NAK_CRS_INFO=1 is for.
#   live     how many values are carried across the nest and mixed inside
#            the loop, to push the register count up without touching the
#            control flow at all.
#
# The three input regimes are a push constant and not a knob here: mode 0
# nobody enters the nest, mode 1 everybody walks to the bottom, mode 2 the
# two lanes of every quad take different depths. A shader compiled with a
# reservation and never entered, entered uniformly, and entered
# divergently are three different questions about one binary.
#
# Copyright (c) mesa-nvk-horizon contributors
# SPDX-License-Identifier: MIT
import argparse
import os
import sys

# (stem, levels, live, one-line purpose)
#
# The deep pair is at 20 rather than 17 so that it is clear of whatever
# from_nir counts on top of the `if`s — the loop pushes too, and a source
# that lands exactly on the boundary would make the reservation an
# accident of counting rather than a chosen variable. The measurement in
# the log is what settles which side of sixteen each one landed on.
VARIANTS = [
    ("crs_mx_a", 4, 2,
     "shallow nest, 2 live: neither knob turned up"),
    ("crs_mx_b", 4, 24,
     "shallow nest, 24 live: some registers, no reservation"),
    ("crs_mx_c", 20, 2,
     "deep nest, 2 live: a reservation without the registers"),
    ("crs_mx_d", 20, 24,
     "deep nest, 24 live: a reservation and some registers"),
    ("crs_mx_e", 4, 56,
     "shallow nest, 56 live: many registers, no reservation"),
    ("crs_mx_f", 20, 56,
     "deep nest, 56 live: a reservation and many registers"),
    ("crs_mx_g", 4, 104,
     "shallow nest, 104 live: the register count of the shader that "
     "hangs, without its reservation"),
    ("crs_mx_h", 20, 104,
     "deep nest, 104 live: both, at the register count of the shader "
     "that hangs"),
]

# WHY THERE IS A THIRD REGISTER STEP. 24 live values came out of this
# compiler as 32 registers, and the shaders this experiment is about are
# at 64 (Mobile's heaviest fragment shader, which renders) and 112
# (Godot's Forward+ scene shader, which hangs). A pair that does not
# hang at 32 says nothing about 64, so 56 live values is here to reach
# the neighbourhood of the one that works and 104 to reach the one that
# does not. Every value is summed at the end, so they are all live at
# once and the allocator cannot drop one; whether it spills instead is
# in the report, and a variant that spills is measuring something else.

HEADER = """; {stem} -- {purpose}
;
; GENERATED by scripts/gen-crs-matrix.py. Edit that, not this: the four
; shaders of this matrix exist to differ in exactly two numbers, and a
; hand edit to one of them destroys the only property that makes the
; comparison mean anything.
;
;   nesting levels          {levels}
;   values live across them {live}
;
; The compiled convergence-stack depth is NOT the number above: from_nir
; pushes once per divergent construct, the loop included, and sm50's
; crs_size() turns that depth into the reservation the shader program
; header carries. Run the case with NAK_CRS_INFO=1 and read the
; `NAK crs:` line; do not count `if`s here and call it depth.
;
; Push constant: uvec4(n, mode, 0, 0)
;
;   sel  = (x ^ y) & 1
;   cond = mode == 0 ? 0                   nobody enters
;        : mode == 1 ? ALL                 everybody goes all the way in
;        :             sel ? ALL : 1       half go in, half stop at one
;
;   v[k] = (x * (2k+1)) ^ (y + k) ^ n
;   acc = 0; i = 0;
;   if (cond & 1) {{ ... {levels} deep ...
;       for (i = 0; i < n; i++) {{
;           acc += i + 1;
;           for k: v[k] = v[k] * 3 + acc;
;       }}
;   ... }}
;   colour = uvec4(acc, i, cond, sum(v))
;
; A UINT attachment, so the numbers come back exactly.
;
; SPIR-V 1.3 (--target-env vulkan1.1), same reasons as comp_write_id.
;
; Copyright (c) mesa-nvk-horizon contributors
; SPDX-License-Identifier: MIT
"""


def emit(stem, levels, live, purpose):
    all_bits = (1 << levels) - 1
    o = []
    w = o.append

    w(HEADER.format(stem=stem, purpose=purpose, levels=levels, live=live))
    w("               OpCapability Shader")
    w("               OpMemoryModel Logical GLSL450")
    w('               OpEntryPoint Fragment %main "main" %out_colour '
      "%frag_coord")
    w("               OpExecutionMode %main OriginUpperLeft")
    w("")
    w("               OpDecorate %out_colour Location 0")
    w("               OpDecorate %frag_coord BuiltIn FragCoord")
    w("               OpMemberDecorate %PC 0 Offset 0")
    w("               OpDecorate %PC Block")
    w("")
    w("       %void = OpTypeVoid")
    w("     %fnvoid = OpTypeFunction %void")
    w("       %bool = OpTypeBool")
    w("      %float = OpTypeFloat 32")
    w("      %int32 = OpTypeInt 32 1")
    w("       %uint = OpTypeInt 32 0")
    w("    %v4float = OpTypeVector %float 4")
    w("     %v4uint = OpTypeVector %uint 4")
    w("   %ptr_fn_u = OpTypePointer Function %uint")
    w("")
    w("         %PC = OpTypeStruct %v4uint")
    w("     %ptr_pc = OpTypePointer PushConstant %PC")
    w("   %ptr_pc_v = OpTypePointer PushConstant %v4uint")
    w("         %pc = OpVariable %ptr_pc PushConstant")
    w("")
    w("  %ptr_out_v = OpTypePointer Output %v4uint")
    w(" %out_colour = OpVariable %ptr_out_v Output")
    w("   %ptr_in_v = OpTypePointer Input %v4float")
    w(" %frag_coord = OpVariable %ptr_in_v Input")
    w("")
    w("      %int_0 = OpConstant %int32 0")
    w("     %uint_0 = OpConstant %uint 0")
    w("     %uint_1 = OpConstant %uint 1")
    w("     %uint_3 = OpConstant %uint 3")
    w(f"   %uint_all = OpConstant %uint {all_bits}")
    for lvl in range(1, levels):
        w(f"   %uint_b{lvl:<2} = OpConstant %uint {1 << lvl}")
    # Odd multipliers and offsets for the live band, so no two of them
    # are the same expression and none can be folded into another.
    for k in range(live):
        w(f"   %uint_m{k:<2} = OpConstant %uint {2 * k + 1}")
        if k > 0:
            w(f"   %uint_k{k:<2} = OpConstant %uint {k}")
    w("")
    w("       %main = OpFunction %void None %fnvoid")
    w("      %entry = OpLabel")
    w("       %pacc = OpVariable %ptr_fn_u Function")
    w("        %pi  = OpVariable %ptr_fn_u Function")
    for k in range(live):
        w(f"       %pv{k:<3} = OpVariable %ptr_fn_u Function")
    w("               OpStore %pacc %uint_0")
    w("               OpStore %pi %uint_0")
    w("         %cp = OpAccessChain %ptr_pc_v %pc %int_0")
    w("          %c = OpLoad %v4uint %cp")
    w("          %n = OpCompositeExtract %uint %c 0")
    w("       %mode = OpCompositeExtract %uint %c 1")
    w("")
    w("         %fc = OpLoad %v4float %frag_coord")
    w("        %fcx = OpCompositeExtract %float %fc 0")
    w("        %fcy = OpCompositeExtract %float %fc 1")
    w("         %ix = OpConvertFToU %uint %fcx")
    w("         %iy = OpConvertFToU %uint %fcy")
    w("        %xr  = OpBitwiseXor %uint %ix %iy")
    w("       %sel  = OpBitwiseAnd %uint %xr %uint_1")
    w("     %sel_nz = OpINotEqual %bool %sel %uint_0")
    w("   %cond_div = OpSelect %uint %sel_nz %uint_all %uint_1")
    w("        %m1  = OpIEqual %bool %mode %uint_1")
    w("     %cond_a = OpSelect %uint %m1 %uint_all %cond_div")
    w("        %m0  = OpIEqual %bool %mode %uint_0")
    w("       %cond = OpSelect %uint %m0 %uint_0 %cond_a")
    w("")
    for k in range(live):
        off = "%uint_0" if k == 0 else f"%uint_k{k}"
        w(f"      %vm{k:<3} = OpIMul %uint %ix %uint_m{k}")
        w(f"      %vy{k:<3} = OpIAdd %uint %iy {off}")
        w(f"      %vx{k:<3} = OpBitwiseXor %uint %vm{k} %vy{k}")
        w(f"      %vi{k:<3} = OpBitwiseXor %uint %vx{k} %n")
        w(f"               OpStore %pv{k} %vi{k}")
    w("")
    for lvl in range(levels):
        bit = "%uint_1" if lvl == 0 else f"%uint_b{lvl}"
        w(f"      %bit{lvl:<2} = OpBitwiseAnd %uint %cond {bit}")
        w(f"      %cmp{lvl:<2} = OpINotEqual %bool %bit{lvl} %uint_0")
        w(f"               OpSelectionMerge %merge{lvl} None")
        w(f"               OpBranchConditional %cmp{lvl} %then{lvl} "
          f"%merge{lvl}")
        w(f"     %then{lvl:<2} = OpLabel")
        w("")
    w("               OpBranch %l_hdr")
    w("      %l_hdr = OpLabel")
    w("               OpLoopMerge %l_exit %l_cont None")
    w("               OpBranch %l_test")
    w("     %l_test = OpLabel")
    w("        %iv0 = OpLoad %uint %pi")
    w("      %l_lt  = OpULessThan %bool %iv0 %n")
    w("               OpBranchConditional %l_lt %l_body %l_exit")
    w("     %l_body = OpLabel")
    w("        %av0 = OpLoad %uint %pacc")
    w("        %iv1 = OpLoad %uint %pi")
    w("       %sum0 = OpIAdd %uint %av0 %iv1")
    w("       %sum1 = OpIAdd %uint %sum0 %uint_1")
    w("               OpStore %pacc %sum1")
    for k in range(live):
        w(f"      %lv{k:<3} = OpLoad %uint %pv{k}")
        w(f"      %lm{k:<3} = OpIMul %uint %lv{k} %uint_3")
        w(f"      %la{k:<3} = OpIAdd %uint %lm{k} %sum1")
        w(f"               OpStore %pv{k} %la{k}")
    w("               OpBranch %l_cont")
    w("     %l_cont = OpLabel")
    w("        %iv2 = OpLoad %uint %pi")
    w("      %inext = OpIAdd %uint %iv2 %uint_1")
    w("               OpStore %pi %inext")
    w("               OpBranch %l_hdr")
    w("     %l_exit = OpLabel")
    for lvl in range(levels - 1, -1, -1):
        w(f"               OpBranch %merge{lvl}")
        w(f"    %merge{lvl:<2} = OpLabel")
    w("")
    w("       %afin = OpLoad %uint %pacc")
    w("       %ifin = OpLoad %uint %pi")
    prev = None
    for k in range(live):
        w(f"      %fv{k:<3} = OpLoad %uint %pv{k}")
        if prev is None:
            prev = f"%fv{k}"
        else:
            w(f"      %fs{k:<3} = OpIAdd %uint {prev} %fv{k}")
            prev = f"%fs{k}"
    w(f"        %col = OpCompositeConstruct %v4uint %afin %ifin %cond {prev}")
    w("               OpStore %out_colour %col")
    w("               OpReturn")
    w("               OpFunctionEnd")
    return chr(10).join(o) + chr(10)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = os.path.join(os.path.dirname(here), "tests", "shaders")

    stale = []
    for stem, levels, live, purpose in VARIANTS:
        text = emit(stem, levels, live, purpose)
        path = os.path.join(out_dir, stem + ".spvasm")
        if args.check:
            have = ""
            if os.path.exists(path):
                with open(path, encoding="utf-8", newline="") as f:
                    have = f.read()
            if have != text:
                stale.append(stem + ".spvasm")
        else:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            print("gen-crs-matrix: %s.spvasm (%u levels, %u live)"
                  % (stem, levels, live))

    if args.check and stale:
        print("gen-crs-matrix: out of date: " + " ".join(stale))
        return 1
    if args.check:
        print("gen-crs-matrix: OK (%u shaders match the generator)"
              % len(VARIANTS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
