#!/usr/bin/env python3
"""Assemble a SPIR-V assembly source and embed it as a C header.

    scripts/spv-embed.py --spirv-as PROG --spirv-val PROG \
        --target-env ENV -o OUT.h IN.spvasm

WHY SPIR-V ASSEMBLY AND NOT GLSL. The shaders Phase 5 needs have to be
built inside the toolchain container, which has no network, and the base
image has no glslang. SPIRV-Tools is already there — the derived image
builds it with SPIRV_SKIP_EXECUTABLES=OFF because mesa_clc needs the
library — so spirv-as and spirv-val cost nothing to use and add no pin
to toolchain/versions.env. The trade is that the sources are verbose;
the gain is that what the driver is handed is exactly what the file
says, with no compiler in between to explain a surprise away.

WHY IT VALIDATES. NAK has never compiled a shader that then ran. When
the first one misbehaves the question will be "is the driver wrong or is
the shader wrong", and spirv-val answers half of it before the .nro is
built. A validation failure is a build failure here, not a warning.

Copyright (c) mesa-nvk-horizon contributors
SPDX-License-Identifier: MIT
"""
import argparse
import os
import struct
import subprocess
import sys


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spirv-as", required=True)
    ap.add_argument("--spirv-val", required=True)
    ap.add_argument("--target-env", default="vulkan1.1")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("input")
    args = ap.parse_args()

    # Beside the output, never in /tmp: the container mounts the tree and
    # nothing else, so a temporary file anywhere outside it is invisible
    # to the host and lost when the container exits.
    spv = args.output + ".spv"

    for cmd in (
        [args.spirv_as, "--target-env", args.target_env,
         args.input, "-o", spv],
        [args.spirv_val, "--target-env", args.target_env, spv],
    ):
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout)
            sys.stderr.write(proc.stderr)
            sys.stderr.write("spv-embed: %s failed on %s\n"
                             % (os.path.basename(cmd[0]), args.input))
            return 1

    with open(spv, "rb") as f:
        blob = f.read()

    # A SPIR-V module is a stream of 32-bit words and the header's first
    # one is the magic. Checked rather than assumed: a truncated or
    # byte-swapped module would otherwise be embedded and only fail
    # inside vkCreateShaderModule on a console.
    if len(blob) % 4 != 0 or len(blob) < 20:
        sys.stderr.write("spv-embed: %s is %d bytes, not a SPIR-V module\n"
                         % (spv, len(blob)))
        return 1
    words = struct.unpack("<%dI" % (len(blob) // 4), blob)
    if words[0] != 0x07230203:
        sys.stderr.write("spv-embed: %s starts with 0x%08x, not the SPIR-V "
                         "magic (0x07230203)\n" % (spv, words[0]))
        return 1

    stem = os.path.basename(args.input)
    for suffix in (".spvasm", ".spv"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
    symbol = "".join(c if c.isalnum() else "_" for c in stem)

    src = os.path.relpath(args.input).replace("\\", "/")
    out = [
        "/* GENERATED by scripts/spv-embed.py from %s -- do not edit.\n"
        " * SPIR-V version %d.%d, %d words, validated for %s.\n"
        " */\n" % (src, (words[1] >> 16) & 0xFF, (words[1] >> 8) & 0xFF,
                   len(words), args.target_env),
        "/* Include guard, because the array is a file-scope definition\n"
        " * and a second include is a redefinition error rather than a\n"
        " * no-op. Two tests already share a shader; a third sharing one\n"
        " * twice in a translation unit should not be a build failure.\n"
        " * Found in review of PR #7. */\n",
        "#ifndef HORIZON_SPV_%s_H\n#define HORIZON_SPV_%s_H\n\n"
        % (symbol.upper(), symbol.upper()),
        "#include <stdint.h>\n\n",
        "static const uint32_t %s_spv[] = {\n" % symbol,
    ]
    for i in range(0, len(words), 6):
        row = ", ".join("0x%08x" % w for w in words[i:i + 6])
        out.append("   %s,\n" % row)
    out.append("};\n\n")
    out.append("#endif /* HORIZON_SPV_%s_H */\n" % symbol.upper())

    with open(args.output, "w") as f:
        f.write("".join(out))

    # The intermediate .spv is meson's business too: it is written
    # beside the output and was declared to nothing, so a clean build
    # left it behind and no rule knew it existed. Removing it here
    # keeps the build directory describable by the build system that
    # owns it. Found in review of PR #7.
    try:
        os.unlink(spv)
    except OSError:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
